[refactor]:

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -33,11 +33,17 @@ fi
 
 # Download tar.gz file to the download directory
 if [[ ! -e "${ASDF_DOWNLOAD_PATH}/$release_file" ]]; then
-    download_release "$ASDF_INSTALL_VERSION" "$release_file"
+	url="$GH_REPO/releases/download/${ASDF_INSTALL_VERSION}/${release_file}"
+	echo "* Downloading $TOOL_NAME release $ASDF_INSTALL_VERSION..."
+    # TODO use gh release download if available
+	curl "${curl_opts[@]}" -o "${ASDF_DOWNLOAD_PATH}/$release_file" -C - "$url" || fail "Could not download $url"
+
 fi
 
 #  Extract contents of tar.gz file into the download directory
-unzip -o "${ASDF_DOWNLOAD_PATH}/$release_file" -d "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+echo "* Extracting..."
+unzip -o "${ASDF_DOWNLOAD_PATH}/"*.zip -d "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
 
 # Remove the tar.gz file since we don't need to keep it
-rm "${ASDF_DOWNLOAD_PATH}/$release_file"
+echo "* Cleaning up..."
+rm "${ASDF_DOWNLOAD_PATH}/"*.zip
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -13,4 +13,23 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 # shellcheck source=../lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
-install_version "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH/bin"
+[[ "$ASDF_INSTALL_TYPE" = "version" ]] || fail "asdf-$TOOL_NAME supports release installs only"
+
+arch=$(uname -m)
+
+(
+    mkdir -p "$ASDF_INSTALL_PATH/bin"
+    echo "* Copying into: $ASDF_INSTALL_PATH/bin"
+    cp -r \
+        "${ASDF_DOWNLOAD_PATH}/${TOOL_NAME}_v${ASDF_INSTALL_VERSION}"*"$arch"/*  \
+        "$ASDF_INSTALL_PATH/bin"
+
+
+    tool_cmd="${TOOL_NAME}_v${ASDF_INSTALL_VERSION}"*"$arch"
+    test -x "$ASDF_INSTALL_PATH/$tool_cmd" || fail "Expected $ASDF_INSTALL_PATH/$tool_cmd to be executable."
+
+    echo "* $TOOL_NAME $ASDF_INSTALL_VERSION installation was successful!"
+) || (
+    rm -rf "$ASDF_INSTALL_PATH"
+    fail "An error occurred while installing $TOOL_NAME $ASDF_INSTALL_VERSION."
+)
